# makefile
all:

#	Compila la clase Persona
		# g++ -c ./tests/ej3TEST.cpp
		# g++ -c ./*.cpp
		# g++  *.o /usr/lib/libgtest.a -o tp -fPIC -O2 -g -fprofile-arcs -ftest-coverage --coverage -Wall -lpthread


		g++ -c ./anagramas/src/*.cpp
		# g++ -c ./bin-package/src/*.cpp
		g++  *.o /usr/lib/libgtest.a -fPIC -O2 -g -fprofile-arcs -ftest-coverage --coverage -Wall -lpthread -o labo10


	rm -r *.o
	#rm ./Calculator-program.bin
	
	#-g --coverage
	