# makefile
all:

#	Compila la clase Persona
		g++ -c ./ej1/esPrimo.cpp
		g++ -c ./ej1/Test/esPrimoTest.cpp
		g++ ./main.cpp esPrimo.o esPrimoTest.o /usr/lib/libgtest.a -o ej -fPIC -O2 -g -Wall -lpthread


	rm -r *.o
	#rm ./Calculator-program.bin
	
	
	