# makefile
all:

#	Compila la clase Persona
		g++ -c ./ej2/llenarTaxis.cpp
		g++ -c ./ej2/Test/llenarTaxisTEST.cpp
		g++ ./main.cpp llenarTaxis.o llenarTaxisTEST.o /usr/lib/libgtest.a -o ej -fPIC -O2 -g -Wall -lpthread


	rm -r *.o
	#rm ./Calculator-program.bin
	
	
	